export const fakeVehicles = [
  {
    _id: '1',
    vehicleName: 'Toyota Corolla',
    owner: 'Farhan Ahmed',
    category: 'Sedan',
    pricePerDay: 70,
    location: 'Dhaka, Bangladesh',
    availability: 'Available',
    description: 'Comfortable 5-seater with A/C and GPS, perfect for city rides.',
    coverImage: 'https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg',
    userEmail: 'farhan@example.com',
    createdAt: '2025-10-29T10:30:00+00:00',
  },
  {
    _id: '2',
    vehicleName: 'Nissan X-Trail',
    owner: 'Samira Rahman',
    category: 'SUV',
    pricePerDay: 95,
    location: 'Chattogram, Bangladesh',
    availability: 'Available',
    description: 'Spacious SUV with great comfort for family trips.',
    coverImage: 'https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg',
    userEmail: 'samira@example.com',
    createdAt: '2025-10-28T09:15:00+00:00',
  },
  {
    _id: '3',
    vehicleName: 'Tesla Model 3',
    owner: 'Rakib Hasan',
    category: 'Electric',
    pricePerDay: 150,
    location: 'Dhaka, Bangladesh',
    availability: 'Available',
    description: 'Electric sedan with autopilot and premium interior.',
    coverImage: 'https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg',
    userEmail: 'rakib@example.com',
    createdAt: '2025-10-27T14:00:00+00:00',
  },
  {
    _id: '4',
    vehicleName: 'Toyota Hiace',
    owner: 'Jannat Akter',
    category: 'Van',
    pricePerDay: 110,
    location: 'Sylhet, Bangladesh',
    availability: 'Booked',
    description: 'Great choice for group tours with comfortable seating.',
    coverImage: 'https://images.pexels.com/photos/112460/pexels-photo-112460.jpeg',
    userEmail: 'jannat@example.com',
    createdAt: '2025-10-26T08:45:00+00:00',
  },
  {
    _id: '5',
    vehicleName: 'Honda Civic',
    owner: 'Shafin Islam',
    category: 'Sedan',
    pricePerDay: 80,
    location: 'Rajshahi, Bangladesh',
    availability: 'Available',
    description: 'Sporty sedan with great mileage and modern features.',
    coverImage: 'https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg',
    userEmail: 'shafin@example.com',
    createdAt: '2025-10-25T13:20:00+00:00',
  },
  {
    _id: '6',
    vehicleName: 'Hyundai Ioniq 5',
    owner: 'Nusrat Jahan',
    category: 'Electric',
    pricePerDay: 160,
    location: 'Dhaka, Bangladesh',
    availability: 'Available',
    description: 'Futuristic electric SUV with fast charging support.',
    coverImage: 'https://images.pexels.com/photos/1402787/pexels-photo-1402787.jpeg',
    userEmail: 'nusrat@example.com',
    createdAt: '2025-10-24T11:10:00+00:00',
  },
];
